# Site settings
title: gooo000
email: gooo000@free.com
description: > # this means to ignore newlines until "baseurl:"
    Hello World!
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://gooo000.github.io" # the base hostname & protocol for your site
twitter_username: gooo000
github_username:  gooo000

# Build settings
markdown: kramdown
